# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"

install:
  - "pip install ."
  - "pip install django-tools coveralls"

script:
  - coverage run ./setup.py test

after_success:
  coveralls

notifications:
  irc: "irc.freenode.org#pylucid"