# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO=1.7
    - DJANGO=1.8

install:
    - pip install --upgrade pip
    - pip install . --no-deps
    - pip install Django==$DJANGO.\* django-tools coveralls

script:
    - coverage run --source=reversion_compare ./setup.py test

after_success:
    - coveralls

notifications:
    irc: "irc.freenode.org#pylucid"