# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - DJANGO='1.8' REVERSION='1.9'
    - DJANGO='1.8' REVERSION='1.10.1'
    - DJANGO='1.9' REVERSION='1.10'

install:
    - pip install --upgrade pip
    - pip install Django==$DJANGO.\*
    - pip install django-reversion==$REVERSION.\*
    - pip install . django-tools coveralls

script:
    - python --version
    - pip freeze
    - coverage run --source=reversion_compare runtests.py

after_success:
    - coverage combine
    - coverage report
    - coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
